###Dataset
In this homework, we will use the California Housing Prices from [Kaggle](https://www.kaggle.com/datasets/camnugent/california-housing-prices).

In [188]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

--2023-09-25 09:41:33--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1423529 (1.4M) [text/plain]
Saving to: ‘housing.csv.13’

housing.csv.13      100%[===================>]   1.36M  6.28MB/s    in 0.2s

2023-09-25 09:41:34 (6.28 MB/s) - ‘housing.csv.13’ saved [1423529/1423529]

###Import dependecies

In [189]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.metrics import mean_squared_error
from sklearn.impute import SimpleImputer

###Load data

In [190]:
df = pd.read_csv('housing.csv')
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

###Filter by ocean proximity

In [191]:
df = df[df['ocean_proximity'].isin(['<1H OCEAN', 'INLAND'])]
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
701,-121.97,37.64,32.0,1283.0,194.0,485.0,171.0,6.0574,431000.0,<1H OCEAN
830,-121.99,37.61,9.0,3666.0,711.0,2341.0,703.0,4.6458,217000.0,<1H OCEAN
859,-121.97,37.57,21.0,4342.0,783.0,2172.0,789.0,4.6146,247600.0,<1H OCEAN
860,-121.96,37.58,15.0,3575.0,597.0,1777.0,559.0,5.7192,283500.0,<1H OCEAN
861,-121.98,37.58,20.0,4126.0,1031.0,2079.0,975.0,3.6832,216900.0,<1H OCEAN
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

Select columns

In [192]:
df = df[[
    'latitude',
    'longitude',
    'housing_median_age',
    'total_rooms',
    'total_bedrooms',
    'population',
    'households',
    'median_income',
    'median_house_value'
]]
df

,latitude,longitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
701,37.64,-121.97,32.0,1283.0,194.0,485.0,171.0,6.0574,431000.0
830,37.61,-121.99,9.0,3666.0,711.0,2341.0,703.0,4.6458,217000.0
859,37.57,-121.97,21.0,4342.0,783.0,2172.0,789.0,4.6146,247600.0
860,37.58,-121.96,15.0,3575.0,597.0,1777.0,559.0,5.7192,283500.0
861,37.58,-121.98,20.0,4126.0,1031.0,2079.0,975.0,3.6832,216900.0
...,...,...,...,...,...,...,...,...,...
20635,39.48,-121.09,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0
20636,39.49,-121.21,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0
20637,39.43,-121.22,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0
20638,39.43,-121.32,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0
20639,39.37,-121.24,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0

###Question 1
There's one feature with missing values. What is it?

- `total_room`
- `total_bedrooms`
- `population`
- `households`

In [193]:
missing_column = df.columns[df.isna().any()].tolist()[0]
print("Column with missing values:", missing_column)

Column with missing values: total_bedrooms

###Question 2
What's the median (50% percentile) for variable 'population'?

- `995`
- `1095`
- `1195`
- `1295`

In [194]:
print("Median population:", df['population'].quantile(0.5))

Median population: 1195.0

###Prepare and split the dataset
- Shuffle the dataset (the filtered one you created above), use seed `42`.
- Split your data in train/val/test sets, with 60%/20%/20% distribution.
- Apply the log transformation to the `median_house_value` variable using the `np.log1p()` function.

In [195]:
# Prepare and split the dataset
data_shuffled = df.sample(frac=1, random_state=42)
train, temp = train_test_split(data_shuffled, test_size=0.4, random_state=42)
val, test = train_test_split(temp, test_size=0.5, random_state=42)

# Apply log transformation
for df_ in [train, val, test]:
    df_['median_house_value'] = np.log1p(df_['median_house_value'])

###Question 3
- We need to deal with missing values for the column from Q1.
- We have two options: fill it with `0` or with the mean of this variable.
- Try both options. For each, train a linear regression model without regularization using the code from the lessons.
- For computing the mean, use the training only!
- Use the validation dataset to evaluate the models and compare the RMSE of each option.
- Round the RMSE scores to 2 decimal digits using `round(score, 2)`
- Which option gives better RMSE?

##### **Options**:

- With `0`
- With mean
- Both are equally good

In [196]:
# Fill missing values with 0
train_zero_filled = train.copy()
train_zero_filled[missing_column].fillna(0, inplace=True)

val_zero_filled = val.copy()
val_zero_filled[missing_column].fillna(0, inplace=True)

# Fill missing values with mean
mean_value = train[missing_column].mean()
train_mean_filled = train.copy()
train_mean_filled[missing_column].fillna(mean_value, inplace=True)

val_mean_filled = val.copy()
val_mean_filled[missing_column].fillna(mean_value, inplace=True)

# Train models and compute RMSE
def train_linear_regression(X, y):
    model = LinearRegression()
    model.fit(X, y)
    return model

def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))

X_train_zero = train_zero_filled.drop('median_house_value', axis=1)
y_train_zero = train_zero_filled['median_house_value']

X_val_zero = val_zero_filled.drop('median_house_value', axis=1)
y_val_zero = val_zero_filled['median_house_value']

model_zero = train_linear_regression(X_train_zero, y_train_zero)
y_pred_zero = model_zero.predict(X_val_zero)
rmse_zero = rmse(y_val_zero, y_pred_zero)

print("RMSE with 0:", round(rmse_zero, 2))

X_train_mean = train_mean_filled.drop('median_house_value', axis=1)
y_train_mean = train_mean_filled['median_house_value']

X_val_mean = val_mean_filled.drop('median_house_value', axis=1)
y_val_mean = val_mean_filled['median_house_value']

model_mean = train_linear_regression(X_train_mean, y_train_mean)
y_pred_mean = model_mean.predict(X_val_mean)
rmse_mean = rmse(y_val_mean, y_pred_mean)

print("RMSE with mean:", round(rmse_mean, 2))

RMSE with 0: 0.35
RMSE with mean: 0.35

###Question 4
- Now let's train a regularized linear regression.
- For this question, fill the NAs with 0.
- Try different values of `r` from this list: `[0, 0.000001, 0.0001, 0.001, 0.01, 0.1, 1, 5, 10]`.
- Use RMSE to evaluate the model on the validation dataset.
- Round the RMSE scores to 2 decimal digits.
- Which r gives the best RMSE?
If there are multiple options, select the smallest r.

Options:

- `0`
- `0.000001`
- `0.001`
- `0.0001`

In [200]:
r_values = [0, 0.000001, 0.0001, 0.001, 0.01, 0.1, 1, 5, 10]
best_rmse = float('inf')
best_r = None

for r in r_values:
    model = Ridge(alpha=r)
    model.fit(X_train_zero, y_train_zero)
    y_pred = model.predict(X_val_zero)
    current_rmse = rmse(y_val_zero, y_pred)
    if current_rmse < best_rmse:
        best_rmse = current_rmse
        best_r = r

print("Best r value:", best_r)

Best r value: 0

###Question 5
- We used seed 42 for splitting the data. Let's find out how selecting the seed influences our score.
- Try different seed values: `[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]`.
- For each seed, do the train/validation/test split with 60%/20%/20% distribution.
- Fill the missing values with 0 and train a model without regularization.
- For each seed, evaluate the model on the validation dataset and collect the RMSE scores.
- What's the standard deviation of all the scores? To compute the standard deviation, use `np.std`.
- Round the result to 3 decimal digits `(round(std, 3))`

What's the value of std?

- `0.5`
- `0.05`
- `0.005`
- `0.0005`

>Note: Standard deviation shows how different the values are. If it's low, then all values are approximately the same. If it's high, the values are different. If standard deviation of scores is low, then our model is stable.

In [201]:
seeds = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
rmse_scores = []

for seed in seeds:
    # Splitting the dataset
    data_shuffled = df.sample(frac=1, random_state=seed)
    train, temp = train_test_split(data_shuffled, test_size=0.4, random_state=seed)
    val, test = train_test_split(temp, test_size=0.5, random_state=seed)

    # Apply log transformation
    train['median_house_value'] = np.log1p(train['median_house_value'])
    val['median_house_value'] = np.log1p(val['median_house_value'])

    # Filling missing values with 0
    train[missing_column].fillna(0, inplace=True)
    val[missing_column].fillna(0, inplace=True)

    # Training the model
    X_train = train.drop('median_house_value', axis=1)
    y_train = train['median_house_value']
    X_val = val.drop('median_house_value', axis=1)
    y_val = val['median_house_value']

    model = train_linear_regression(X_train, y_train)
    y_pred = model.predict(X_val)
    rmse_scores.append(rmse(y_val, y_pred))

std_rmse = round(np.std(rmse_scores), 3)
print("Standard deviation of RMSE scores:", std_rmse)

Standard deviation of RMSE scores: 0.006

###Question 6
Split the dataset like previously, use seed 9.
Combine train and validation datasets.
Fill the missing values with 0 and train a model with r=0.001.
What's the RMSE on the test dataset?

Options:

- `0.13`
- `0.23`
- `0.33`
- `0.43`

In [202]:
# Splitting the dataset with seed 9
data_shuffled = df.sample(frac=1, random_state=9)
train, temp = train_test_split(data_shuffled, test_size=0.4, random_state=9)
val, test = train_test_split(temp, test_size=0.5, random_state=9)

# Combining train and validation datasets
train_combined = pd.concat([train, val])

# Apply log transformation
train_combined['median_house_value'] = np.log1p(train_combined['median_house_value'])
test['median_house_value'] = np.log1p(test['median_house_value'])

# Filling missing values with 0
train_combined[missing_column].fillna(0, inplace=True)
test[missing_column].fillna(0, inplace=True)

# Training the model with r=0.001
X_train_combined = train_combined.drop('median_house_value', axis=1)
y_train_combined = train_combined['median_house_value']
X_test = test.drop('median_house_value', axis=1)
y_test = test['median_house_value']

model = Ridge(alpha=0.001)
model.fit(X_train_combined, y_train_combined)
y_pred_test = model.predict(X_test)
rmse_test = round(rmse(y_test, y_pred_test), 2)

print("RMSE on the test dataset:", rmse_test)

RMSE on the test dataset: 0.33